### ISSUE TITLE
Vitesse 7429 mips support question 

### ISSUE THREAD

**Issue by BruceLavoie** [vtss/openocd-config-vtss#2]
My hardware platform is built using a Vitesse MIPS 7429 switch chip and I'm using OpenOCD on a Ubuntu 14.04 VMware quest OS on a Windows 7 host.  From the following error messages that I'm seeing below, I believe that my flyswatter2 is in fact connecting to the JTAG tap however the luton26 and luton10 config files are not recognizing the tap controller because of some kind of ID.  

development@ubuntu:~$ openocd -f interface/ftdi/flyswatter2.cfg -f vtss/luton10.cfg
Open On-Chip Debugger 0.10.0-dev-00001-g70a14db (2015-06-18-06:42)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
trst_and_srst separate srst_gates_jtag trst_push_pull srst_open_drain connect_deassert_srst
adapter speed: 6000 kHz
target_init
Info : clock speed 6000 kHz
Info : JTAG tap: luton26.cpu tap/device found: 0x300310e9 (mfg: 0x074, part: 0x0031, ver: 0x3)
Warn : JTAG tap: luton26.cpu       UNEXPECTED: 0x300310e9 (mfg: 0x074, part: 0x0031, ver: 0x3)
Error: JTAG tap: luton26.cpu  expected 1 of 1: 0x000310e9 (mfg: 0x074, part: 0x0031, ver: 0x0)
Error: Trying to use configured scan chain anyway...
Warn : Bypassing JTAG setup events due to errors

development@ubuntu:~$ openocd -f interface/ftdi/flyswatter2.cfg -f vtss/luton26.cfg
Open On-Chip Debugger 0.10.0-dev-00001-g70a14db (2015-06-18-06:42)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
trst_and_srst separate srst_gates_jtag trst_push_pull srst_open_drain connect_deassert_srst
adapter speed: 6000 kHz
target_init
Info : clock speed 6000 kHz
Info : JTAG tap: luton26.cpu tap/device found: 0x300310e9 (mfg: 0x074, part: 0x0031, ver: 0x3)
Warn : JTAG tap: luton26.cpu       UNEXPECTED: 0x300310e9 (mfg: 0x074, part: 0x0031, ver: 0x3)
Error: JTAG tap: luton26.cpu  expected 1 of 1: 0x000310e9 (mfg: 0x074, part: 0x0031, ver: 0x0)
Error: Trying to use configured scan chain anyway...
Warn : Bypassing JTAG setup events due to errors

Once I've established connection and I try to debug my CEServices.elf file with GDB

 development@ubuntu:~$ cd vitessesdk/CEServices/build/
development@ubuntu:~/vitessesdk/CEServices/build$ mipsel-vtss-elf-gdb obj/CEServices.elf
GNU gdb (crosstool-NG 1.20.0 - vtss-eCos-toolchain-v2) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_unknown-linux-gnu --target=mipsel-vtss-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from obj/CEServices.elf...done.
(gdb) target remote localhost:3333
Remote debugging using localhost:3333
0x00000000 in ?? ()
(gdb) 

Once the connection has been attempted with the GDB, the first window comes back with 

Error: timed out while waiting for target halted
TARGET: luton26.cpu - Not halted
in procedure 'reset' 
in procedure 'ocd_bouncer'

I'd really like to understand what the issue is, could it be possible that there is a hardware issue or could it be the fact that the config file needs to be updated to fully support this device?

any help is greatly appreciated.

-Bruce

Info : Halt timed out, wake up GDB.

**Comment by lpovlsen** [comment]
Hi Bruce!

The disagreement on JTAG id is due to you having a subsequent chip revision - its fine to update that to <b>0x300310e9</b> (in vtss/target/luton26.cfg).

This should rid the warning, but it won't affect the issue you are seeing...

However, you may find that the <b>adapter_khz</b> setting may be too agresssive for all board designs - you might want to lower that to get stable operation.

Hope that helps.

---Lars

PS: Please note that the configs depends on the bootloader being present (in flash) on the board. You should be able to see the bootloader print the version prompt when you connect with GDB. (Or directly to the monitor and do a "reset run"). If not, somethings too broken... If that is the case I need more info about how the boards behaves.

**Comment by BruceLavoie** [comment]
Thank you so much for your help and I went back to the board connections and I had issue with the nReset signal.  After soldering the problem was fixed.  I haven't changed the config file yet to fix the revision ID and adapter speed yet, but I will.

I've made a lot of progress with this, but now I'm facing an issue with GDB.  

When I launch GDB as follows.
----------------------------------------------
development@ubuntu:~/vitessesdk/CEServices/build/obj$ mipsel-vtss-elf-gdb CEServices.elf
GNU gdb (crosstool-NG 1.20.0 - vtss-eCos-toolchain-v2) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_unknown-linux-gnu --target=mipsel-vtss-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from CEServices.elf...done.
------------------------------------------------------------------
(gdb) target remote localhost:3333
Remote debugging using localhost:3333
0x80008da0 in ?? ()
(gdb) list
78	/home/development/vitesseSDK/CEServices/build/../third_party/eCos/packages/language/c/libc/startup/current/src/main.cxx: No such file or directory.
(gdb) step
Cannot find bounds of current function
 
When I do a listing in the directory it's in there?
development@ubuntu:~/vitessesdk/CEServices/build$ ls ../third_party/eCos/packages/language/c/libc/startup/current/src/main.cxx
../third_party/eCos/packages/language/c/libc/startup/current/src/main.cxx
development@ubuntu:~/vitessesdk/CEServices/build$

Any idea why this might be happening?

**Comment by lpovlsen** [comment]
Hi Bruce!

Glad you got some progress.

Wrt. the present issue, I see whats happening.

When you are connecting with GDB, you are left with the CPU being intercepted somewhere after the redboot power-on (initializing DDR, issueing the serial prompt, etc.).

At this time, you need to issue the gdb `load` command in order to download your `.elf` file.

GDB is acting up because it can't correlate the CPU/stack state to the symbols present in the `CEServices.elf` file - which is quite reasonable...

So just do the `load` and then `continue` and you should be fine. (You can also set a breakpoint somewhere before the `continue` in case you want to regain control at a specific point).

Cheers,

---Lars

**Comment by BruceLavoie** [comment]
Thank you so much, I'm rolling now.  I really appreciate the help.
